import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import EventList from "../../components/events/event-list";
import EventsSearch from "../../components/events/events-search";
import { getAllEvents } from "../../dummy-data";

const AllEventsPage: NextPage = () => {
  const router = useRouter();

  const events = getAllEvents();
  const findEventsHandler = (year: string, month: string) => {
    router.push(`/events/${year}/${month}`);
  };
  return (
    <>
      <Head>
        <title>AllEvents</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <EventsSearch onSearch={findEventsHandler} />
        <EventList items={events} />
      </>
    </>
  );
};

export default AllEventsPage;
